config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  root to: 'public/homes#top'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :shops
    resources :posts, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :show, :destroy]
  end

  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy] do
      collection do
        get :unsubscribe
      end
    end
    resources :shops, only: [:index, :show] do
      resources :reviews do
        resources :comments, only: [:create, :destroy]
      end
    end
    resources :posts
    resources :tags do
      get 'posts', to: 'posts#index'
    end
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :image

  validates :image, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :telepone, presence: true
  validates :open_time, presence: true
  validates :close_time, presence: true
  validates :off_day, presence: true
  validates :website, presence: true

  geocoded_by :get_address
  after_validation :geocode, if: :address_changed?

  def get_address
    self.address
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    shop = Shop.new(shop_params)
    if shop.save
      redirect_to admin_shop_path(shop.id)
    else
      @shop = Shop.new
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to admin_shop_path(@shop.id)
    else
      render :edit
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to admin_shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:image, :name, :address, :telepone, :facsimile, :open_time, :close_time, :off_day, :website, :latitude, :longitude)
  end

end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/views/admin/shops/edit.html.erb
<div class="col-lg-8 col-sm-10 mx-auto">
  <div class="text-center mb-5">
    <h2>店舗情報編集</h2>
  </div>

  <%= form_with model: @shop, url: admin_shop_path do |f| %>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th style="width: 50%">店舗画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th>店舗名</th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= f.text_field :address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= f.text_field :telepone %></td>
        </tr>
        <tr>
          <th>Fax</th>
          <td><%= f.text_field :facsimile %></td>
        </tr>
        <tr>
          <th>営業時間</th>
          <td>
            <%= f.time_select(:open_time, {class: 'select-time', id: "open_time", prompt: '--', time_separator: ':'}, ignore_data: true) %>
            ~
            <%= f.time_select(:close_time, {class: 'select-time', id: "close_time", prompt: '--', time_separator: ':'}, ignore_data: true) %>
          </td>
        </tr>
        <tr>
          <th>店休日</th>
          <td><%= f.text_field :off_day %></td>
        </tr>
        <tr>
          <th>HP</th>
          <td><%= f.text_field :website %></td>
        </tr>
      </tbody>
    </table>
    <div class="actions text-center">
      <%= f.submit '変更を保存する', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/shops/index.html.erb
<deiv class="row mb-5">
  <div class="col"></div>
  <div class="col text-center"><h2>店舗一覧</h2></div>
  <div class="col text-right">
    <%= link_to new_admin_shop_path, class: "btn btn-success" do %>
      <i class="fas fa-store"></i><i class="fas fa-plus"></i>
    <% end %>
  </div>
</deiv><!--row-->

<div class="col-lg-8 col-sm-10 mx-auto">
  <table class="table">
    <thead>
      <tr>
        <th>登録日</th>
        <th>店舗名</th>
        <th>所在地</th>
      </tr>
    </thead>

    <tbody>
      <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.created_at.strftime("%Y/%m/%d") %></td>
        <td>
          <%= link_to admin_shop_path(shop.id), class: "text-dark" do %>
            <%= shop.name %>
          <% end %>
        </td>
        <td><%= shop.address %></td>
      </tr>
      <% end %>
      </tbody>
  </table>
</div>

app/views/admin/shops/new.html.erb
<div class="col-lg-8 col-sm-10 mx-auto">
  <div class="text-center mb-5">
    <h2>店舗登録</h2>
  </div>

  <%= form_with model: [:admin, @shop]  do |f| %>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th style="width: 50%">店舗画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th>店舗名</th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= f.text_field :address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= f.text_field :telepone %></td>
        </tr>
        <tr>
          <th>Fax</th>
          <td><%= f.text_field :facsimile %></td>
        </tr>
        <tr>
          <th>営業時間</th>
          <td>
            <%= f.time_select(:open_time, {class: 'select-time', id: "open_time", prompt: '--', time_separator: ':'}, ignore_data: true) %>
            ~
            <%= f.time_select(:close_time, {class: 'select-time', id: "close_time", prompt: '--', time_separator: ':'}, ignore_data: true) %>
          </td>
        </tr>
        <tr>
          <th>店休日</th>
          <td><%= f.text_field :off_day %></td>
        </tr>
        <tr>
          <th>HP</th>
          <td><%= f.text_field :website %></td>
        </tr>
      </tbody>
    </table>
    <div class="actions text-center">
      <%= f.submit '新規登録', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/shops/show.html.erb
<div class="text-center mb-5">
  <h2>店舗詳細</h2>
</div>

<div class="row">
  <div class="col text-center">
    <%= image_tag @shop.image, size: "300x300" %><br>
  </div>

  <div class="col">
    <table class="table table-borderless">
        <tbody>
          <tr>
            <th>店舗名</th>
            <td><%= @shop.name %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @shop.address %></td>
          </tr>
          <tr>
            <th>電話番号(FAX)</th>
            <td><%= @shop.telepone %>(<%= @shop.facsimile %>)</td>
          </tr>
          <tr>
            <th>営業時間</th>
            <td><%= @shop.open_time.strftime("%H:%M") %> ~ <%= @shop.close_time.strftime("%H:%M") %></td>
          </tr>
          <tr>
            <th>店休日</th>
            <td><%= @shop.off_day %></td>
          </tr>
          <tr>
            <th>HP</th>
            <td><%= @shop.website %></td>
          </tr>
        </tbody>
      </table>
  </div>
</div>

<div class="col-lg-8 col-sm-10 mt-5 mx-auto">
  <%= link_to "編集する", edit_admin_shop_path(@shop.id), class: "btn btn-success w-100 btn-lg mb-3" %>
  <%= link_to "店舗の削除", admin_shop_path(@shop.id), method: :delete, "data-confirm" => "この店舗を削除しますか？", class: "btn btn-danger w-100 btn-lg" %>
</div>