config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  root to: 'public/homes#top'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :shops
    resources :posts, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :show, :destroy]
  end

  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy] do
      collection do
        get :unsubscribe
      end
    end
    resources :shops, only: [:index, :show] do
      resources :reviews do
        resources :comments, only: [:create, :destroy]
      end
    end
    resources :posts
    resources :tags do
      get 'posts', to: 'posts#index'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  has_many_attached :images
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  validates :title, presence: true
  validates :content, presence: true

  def save_tag!(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tag = Tag.find_by(tag_name: old)
      tag_maps.find_by(tag_id: tag.id).destroy!
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by!(tag_name: new)
      tag_maps.create!(tag_id: new_post_tag.id)
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @posts = @user.posts.all
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="text-center mb-5">
  <h2>投稿一覧</h2>
</div>

<div class="col-lg-8 col-sm-10 mx-auto">
  <table class="table">
    <thead class="thead-success">
      <tr>
        <th>投稿日</th>
          <th>投稿者</th>
          <th>タイトル</th>
          <th>関連店舗</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
        <tr>
          <td><%= post.created_at.strftime("%Y/%m/%d") %></td>
          <td><%= post.user.name %></td>
          <td>
            <%= link_to admin_post_path(post.id), class: "text-dark" do %>
              <%= post.title %>
            <% end %>
          </td>
          <td><%= post.shop.name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/admin/posts/show.html.erb
<div class="text-center mb-5">
  <h2>投稿詳細</h2>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <div class="text-center">
        <% if @user.image.attached? %>
          <%= image_tag @user.image, size: "50x50" %>
        <% else %>
          <%= image_tag 'sweets_icecream.png', size: "50x50" %>
        <% end %>
      </div>

      <table class="table text-center">
        <tbody>
          <tr>
            <td>
              <%= link_to admin_user_path(@user.id), class: "text-dark" do %>
                <%= @user.name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td><%= @user.message %></td>
          </tr>
        </tbody>
      </table>

      <%= link_to "投稿の削除", admin_post_path(@post.id), method: :delete, "data-confirm" => "この投稿を削除しますか？", class: "btn btn-danger w-100" %>
    </div>

    <div class="col-lg-8">
      <div class="mb-3">
        <% if @post.images.attached? %>
          <% @post.images.each do |image| %>
            <%= image_tag image, width: 200, height: 200 %>
          <% end %>
        <% end %>
      </div>

      <table class="table table-borderless">
        <tbody>
          <tr>
            <th style="width: 30%">タイトル</th>
            <td><%= @post.title %></td>
          </tr>
          <tr>
            <th>近くの店舗</th>
            <td><%= @post.shop.name %></td>
          </tr>
          <tr>
            <th>できごと</th>
            <td><%= @post.content %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>