config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  root to: 'public/homes#top'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :shops
    resources :posts, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :show, :destroy]
  end

  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy] do
      collection do
        get :unsubscribe
      end
    end
    resources :shops, only: [:index, :show] do
      resources :reviews do
        resources :comments, only: [:create, :destroy]
      end
    end
    resources :posts
    resources :tags do
      get 'posts', to: 'posts#index'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
  validates :email, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "GUEST"
    end
  end

  def is_guest?
   if  self.email == 'guest@example.com'
     return true
   end
   return false
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      @user = User.find(params[:id])
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :message, :image, :is_active)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="col-lg-8 col-sm-10 mx-auto">
  <h2 class="mb-5 text-center">ユーザー情報変更</h2>

  <%= form_with model: @user, url: admin_user_path(@user.id) do |f| %>
    <%= f.file_field :image, accept: "image/*" %>
    <table class="table table-borderless mb-3">
      <tbody>
        <tr>
          <th style="width: 50%">ユーザーID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th>ユーザーネーム</th>
          <td><%= f.text_field :name, size: 20 %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= f.text_field :email, size: 20 %></td>
        </tr>
        <tr>
          <th>メッセージ</th>
          <td><%= f.text_field :message %></td>
        </tr>
      </tbody>
    </table>

    <div class="actions text-center">
      <%= f.submit '変更を保存する', class: "btn btn-success" %>
    </div>
  <% end %>

</div>

app/views/admin/users/index.html.erb
<div class="col-lg-8 col-sm-10 mx-auto">
  <h2 class="text-center mb-5">ユーザー一覧</h2>
    <table class="table">
      <thead>
        <tr>
          <th>ユーザーID</th>
          <th>ユーザーネーム</th>
          <th>メールアドレス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <th><%= user.id %></th>
          <th>
            <%= link_to admin_user_path(user.id), class: "text-dark" do %>
              <%= user.name %>
            <% end %>
          </th>
          <th><%= user.email %></th>
        </tr>
        <% end %>
      </tbody>
    </table>
</div><!--col-lg-8-->

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col">
    <div class="mb-4 text-center">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, size: "250x250" %>
      <% else %>
        <%= image_tag 'sweets_icecream.png', size: "250x250" %>
      <% end %>
    </div><!--mb-4-->
  </div>

  <div class="col">
    <table class="table table-borderless mx-auto">
        <tbody>
          <tr>
            <th>ユーザーID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th>ユーザーネーム</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>メッセージ</th>
            <td><%= @user.message %></td>
          </tr>
        </tbody>
      </table>
  </div><!--col-->
</div><!--row-->

<div class="row mt-5 text-center">
  <div class="col">
    <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-success w-100" %>
  </div>
  <div class="col">
    <%= link_to "投稿履歴一覧", admin_posts_path(user_id: @user.id), class: "btn btn-success w-100" %>
  </div>
  <div class="col">
    <%= link_to "レビュー一覧", admin_reviews_path(user_id: @user.id), class: "btn btn-success w-100" %>
  </div>
</div>