config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  root to: 'public/homes#top'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :shops
    resources :posts, only: [:index, :show, :destroy]
    resources :reviews, only: [:index, :show, :destroy]
  end

  scope module: :public do
    resources :users, only: [:show, :edit, :update, :destroy] do
      collection do
        get :unsubscribe
      end
    end
    resources :shops, only: [:index, :show] do
      resources :reviews do
        resources :comments, only: [:create, :destroy]
      end
    end
    resources :posts
    resources :tags do
      get 'posts', to: 'posts#index'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  has_many_attached :images
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  validates :title, presence: true
  validates :content, presence: true

  def save_tag!(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tag = Tag.find_by(tag_name: old)
      tag_maps.find_by(tag_id: tag.id).destroy!
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by!(tag_name: new)
      tag_maps.create!(tag_id: new_post_tag.id)
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :ice_name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 99_999 }, format: { with: /\A[0-9]+\z/ }
  validates :feedback, presence:true
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :image

  validates :image, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :telepone, presence: true
  validates :open_time, presence: true
  validates :close_time, presence: true
  validates :off_day, presence: true
  validates :website, presence: true

  geocoded_by :get_address
  after_validation :geocode, if: :address_changed?

  def get_address
    self.address
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps

end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
  validates :email, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "GUEST"
    end
  end

  def is_guest?
   if  self.email == 'guest@example.com'
     return true
   end
   return false
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @posts = @user.posts.all
    else
      @posts = Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @reviews = @user.reviews.all
    else
      @reviews = Review.all
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_reviews_path
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    shop = Shop.new(shop_params)
    if shop.save
      redirect_to admin_shop_path(shop.id)
    else
      @shop = Shop.new
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to admin_shop_path(@shop.id)
    else
      render :edit
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to admin_shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:image, :name, :address, :telepone, :facsimile, :open_time, :close_time, :off_day, :website, :latitude, :longitude)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      @user = User.find(params[:id])
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :message, :image, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "text-dark" %><br />
<% end %>

<!--<#%- if devise_mapping.registerable? && controller_name != 'registrations' %>-->
<!--  <#%= link_to "Sign up", new_registration_path(resource_name) %><br />-->
<!--<"% end %>-->

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか?", new_password_path(resource_name), class: "text-dark" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ice Cream Search</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header class="fixed-top" style="height:200px; background-color:#ffffff;">
        <!--ヘッダー画像-->
        <nav class="navbar navbar-light justify-content-center">
          <a class="" href="/"><%= image_tag 'logo2.png' %></a>
        </nav>

        <!--ヘッダーメニュー-->
        <nav class="navbar navbar-expand" style="background-color:#fecf8d;">
          <div class="container-fluid">
              <ul class="navbar-nav w-50 nav-justified ml-auto mr-auto">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "SHOP", shops_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "POST", posts_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "MY PAGE", user_path(current_user.id), class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                  </li>
                <% elsif admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "USER", admin_users_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "SHOP", admin_shops_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "POST", admin_posts_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "REVIEW", admin_reviews_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "LOG OUT", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "SHOP", shops_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "POST", posts_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "LOG IN", new_user_session_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "SIGN UP", new_user_registration_path, class: 'nav-link text-dark' %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <main class="main">
        <div style="margin-top:200px;"></div>
        <div class="py-5 container"><%= yield %></div>
      </main>

      <footer class="footer">
        <div class="text-center">ロゴは <a href="https://www.designevo.com/jp/" title="無料オンラインロゴメーカー">DesignEvo</a> ロゴメーカーさんに作られる</div>
      </footer>
    </div>
  </body>
</html>